server:
  port: 3030
  servlet:
    context-path: /auth-server

spring:
  application:
    name: auth-server
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:users
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  profile:
    default: default
  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG

eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info