spring:
  application:
    name: report-ms
  profile:
    default: default
  config:
    import: "optional:configserver:http://localhost:7777"
springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /api-docs
server:
  port: 0
  servlet:
    context-path: /report-ms
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG

