spring:
  application:
    name: report-ms
  profiles:
    active: prod
  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"

  cloud:
    stream:
      kafka:
        binder:
          brokers: ${BROKER_URL}
      function:
        bindings:
          consumerReport-out-O:
            destination: consumerReport

springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /api-docs

server:
  port: 7070
  servlet:
    context-path: /report-ms

eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

logging:
  level:
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info

