spring:
  application:
    name: report-listener
  profile:
    default: default

  cloud:
    stream:
      kafka:
        binder:
          brokers: ${BROKER_URL:localhost:9092}
      bindings:
        consumerReport-in-0:
          destination: consumerReport
          group: report-group
      function:
        definition: consumerReport

  data:
    mongodb:
      uri: mongodb://sa:sa@localhost:28017/reports?authSource=admin
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /api-docs

server:
  port: 1010
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

logging:
  level:
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info
