spring:
  profiles:
    active: oauth2

  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    fetch-registry: true
    register-with-eureka: true

server:
  port: 4040

management:
  endpoints:
    web:
      exposure:
        include: health,info