server:
  port: 7777

spring:
  profiles:
    active: default
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: ${GIT_DEFAULT_LABEL:main}
          clone-on-start: true
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

